---
- hosts: all
  become: true
  tasks:
  - name: "Ubuntu - install apache2 and php package"
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: "CentOS - install apache2 and php package"
    dnf:
      name: 
        - httpd
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
